from .tab_documentation import tab_documentation
from .tab_mes_analytics import tab_mes_analytics
from .tab_iron_gate_compliance import tab_iron_gate_compliance
from .tab_weekly_summary import tab_weekly_summary